export const packageUi = {
  heroTitle: "Curated Bhutan Journeys",
  heroDescription: "Explore handcrafted itineraries across Bhutan’s festivals, mountains, and cultural heartland.",
  searchPlaceholder: "Search by region, theme, or experience",
  filters: {
    region: "Region",
    difficulty: "Difficulty",
    duration: "Duration",
    comfort: "Comfort Level",
  },
  overview: "Overview",
  itinerary: "Itinerary",
  gallery: "Gallery",
  inclusions: "Inclusions",
  exclusions: "Not included",
  faqs: "FAQs",
  map: "Map & Route",
  customizeCtaTitle: "Can’t find the perfect itinerary?",
  customizeCtaDescription: "We craft bespoke Bhutan journeys based on your travel style, timing, and pace.",
  customizeCtaButton: "Request a Custom Proposal",
  planPanelTitle: "Plan With Our Bhutan Experts",
  planPanelDescription: "Receive a tailored proposal, vetted accommodations, and licensing support from our local team.",
  mapNote: "We will provide a custom route map after finalizing your itinerary and travel dates.",
}
